name: AI Code Review (Azure OpenAI)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "**" ]
  workflow_dispatch: {}

permissions:
  contents: write           # necessário p/ push automático (opcional)
  pull-requests: write      # necessário p/ comentar na PR

jobs:
  ai-review:
    name: Run AI code review
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}  # pula PR em rascunho

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests unidiff

      - name: Run AI Reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}  # ex: gpt-4o-mini
          AUTO_COMMIT: ${{ vars.AUTO_COMMIT || 'false' }}  # defina como true se quiser aplicar commits auto
        run: |
          python .github/scripts/ai_reviewer.py
